import { forwardRef } from 'react';

const Invoice = forwardRef(({ sale }, ref) => {
  const customer = sale.customer || {};
  const items = [
    { kg: '12 KG', filled: sale.twelve_kg, empty: sale.empty_twelve_kg, price: sale.price_12_kg },
    { kg: '25 KG', filled: sale.twentyfive_kg, empty: sale.empty_twentyfive_kg, price: sale.price_25_kg },
    { kg: '33 KG', filled: sale.thirtythree_kg, empty: sale.empty_thirtythree_kg, price: sale.price_33_kg },
    { kg: '35 KG', filled: sale.thirtyfive_kg, empty: sale.empty_thirtyfive_kg, price: sale.price_35_kg },
    { kg: '45 KG', filled: sale.fourtyfive_kg, empty: sale.empty_fourtyfive_kg, price: sale.price_45_kg },
    { kg: 'Others', filled: sale.others_kg, empty: sale.empty_others_kg, price: 0 },
  ].filter(item => parseInt(item.filled) > 0 || parseInt(item.empty) > 0);

  return (
    <div ref={ref} className="invoice-container max-w-[105mm] mx-auto p-4 font-sans text-sm bg-white border border-gray-200">
      <div className="text-center mb-4">
        <h1 className="text-2xl font-bold">Invoice</h1>
        <p className="text-gray-600">Invoice #{sale.id}</p>
        <p className="text-gray-600">Date: {sale.date}</p>
      </div>

      <div className="mb-4">
        <h2 className="text-lg font-semibold">Customer Information</h2>
        <p><strong>Name:</strong> {customer.name || sale.customer_name || 'N/A'}</p>
        <p><strong>Phone:</strong> {customer.phone || 'N/A'}</p>
        <p><strong>Address:</strong> {customer.address || 'N/A'}</p>
      </div>

      <div className="mb-4">
        <h2 className="text-lg font-semibold">Items</h2>
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="border p-2 text-left">Item</th>
              <th className="border p-2 text-center">Filled</th>
              <th className="border p-2 text-center">Empty</th>
              <th className="border p-2 text-right">Price</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item, index) => (
              <tr key={index}>
                <td className="border p-2">{item.kg}</td>
                <td className="border p-2 text-center">{item.filled}</td>
                <td className="border p-2 text-center">{item.empty}</td>
                <td className="border p-2 text-right">{item.price ? `${item.price} TK` : 'N/A'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="text-right">
        <p><strong>Total Price:</strong> {sale.price} TK</p>
        <p><strong>Paid:</strong> {sale.pay} TK</p>
        <p><strong>Due:</strong> {sale.due} TK</p>
      </div>

      <div className="mt-4 text-center text-gray-500">
        <p>Thank you for your business!</p>
        <p>Generated by Your Company Name</p>
      </div>
    </div>
  );
});

export default Invoice;